on: 
  pull_request: 
    types:
      - opened
    branches:
      - main
    paths: 
      - "!.github/**"
      - .github/workflows/build-integration-local.yml
      - integrations/local/**
  
jobs: 
  run_test: 
    runs-on: 
      - ubuntu-latest
    permissions: 
      contents: read
    steps: 
      - uses: actions/checkout@v3
      - run: curl -fsSL https://synap.sh/install | bash
      - run: echo "SYNAPSE_INSTALL=$HOME/.synapse" >> "$GITHUB_ENV"
      - run: echo "${SYNAPSE_INSTALL}/bin" >> "$GITHUB_PATH"
      - run: synapse --version
      - run: cd integrations/local && synapse compile && synapse publish --local
        name: Build
      - run: cd test/conformance && synapse compile && synapse test && synapse destroy
        name: Test
