on: 
  push:
    branches:
      - main
    paths: 
      - "!.github/**"
      - .github/workflows/build-synapse.yml
      - src/**
  pull_request: 
    branches:
      - main
    paths: 
      - "!.github/**"
      - .github/workflows/build-synapse.yml
      - src/**
  
jobs: 
  run_test: 
    runs-on: 
      - ubuntu-latest
    permissions: 
      contents: read
    steps: 
      - uses: actions/checkout@v3
      - run: curl -fsSL https://synap.sh/install | bash
      - run: echo "SYNAPSE_INSTALL=$HOME/.synapse" >> "$GITHUB_ENV"
      - run: echo "${SYNAPSE_INSTALL}/bin" >> "$GITHUB_PATH"
      - run: synapse --version
      - run: synapse compile && synapse build
      - run: ./dist/bin/synapse
