on: 
  push:
    branches:
      - main
    paths: 
      - "!.github/**"
      - .github/workflows/build-synapse.yml
      - src/**
      - test/**
  pull_request: 
    branches:
      - main
    paths: 
      - "!.github/**"
      - .github/workflows/build-synapse.yml
      - src/**
      - test/**

jobs: 
  run_test:
    strategy:
      matrix:
        include:
          - os: macos-13
          - os: macos-14
          - os: ubuntu-latest
          - os: windows-2022
    runs-on: ${{ matrix.os }}
    permissions: 
      contents: read
    steps: 
      - uses: actions/checkout@v3

      - run: curl -fsSL https://synap.sh/install | bash
        if: matrix.os != 'windows-2022'
      - run: irm https://synap.sh/install.ps1 | iex
        if: matrix.os == 'windows-2022'
      - run: synapse --version

      - run: synapse compile
      - run: synapse run testFixtures
        if: matrix.os != 'windows-2022' # TODO: need bash to run the fixture tests
      - run: synapse build
      - run: ./dist/bin/synapse
