on: 
  pull_request: 
    branches:
      - main
    paths: 
      - "!.github/**"
      - .github/workflows/build-integration-local.yml
      - integrations/local/**
  
jobs: 
  run_test: 
    runs-on: 
      - ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: Cohesible/get-credentials-action@d2795224e6f0ea7b2e41c4d3dbdb8bc3c873f450
      - uses: actions/checkout@v3
      - run: curl -fsSL https://synap.sh/install | bash
      - run: synapse --version
      - run: cd integrations/local && synapse compile && synapse publish --local
        name: Build
      - run: cd test/conformance && synapse compile && synapse test && synapse destroy
        name: Test
