on: 
  push:
    branches:
      - main
    paths: 
      - "!.github/**"
      - .github/workflows/test-action.yml
      - src/**
  
jobs: 
  run_test: 
    runs-on: 
      - ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps: 
      - uses: Cohesible/get-credentials-action@d2795224e6f0ea7b2e41c4d3dbdb8bc3c873f450

